---
version: '2'
services:
  # watcher application (websocket bridge between browser and HW)
  watcher:
    devices:
      - "/dev/ttyUSB0"
    volumes:
      - $PWD/watcher/watcher:/src
    # environment:
    #   LED_OFF: 1
